jetbrains:
  plugins:
    - com.intellij.selenium
    - aws.toolkit

  intellij:
    vmoptions: -Didea.plugin.hosts="https://3000-andreafalze-gitpodjbcus-8b8bbp3yk9w.ws-eu71.gitpod.io/updatePlugins.xml"  
#    vmoptions: -Dhttp.proxyHost=localhost -Dhttp.proxyPort=2019 -Dhttp.nonProxyHosts="localhost|gitpod.io|plugins.jetbrains.com"  
#    vmoptions: -Didea.plugins.host="xxxplugins.jetbrains.com"  
